"""add forecast_runs and forecast_points tables

Revision ID: 3f3e08842422
Revises: 0002_encoder_barangay_schema
Create Date: 2026-09-03 02:17:00.696846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f3e08842422'
down_revision = '0002_encoder_barangay_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('readiness', sa.String(length=20), nullable=False),
    sa.Column('reliability', sa.String(length=20), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('expected_change_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('projected_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('expected_change_pct IS NULL OR expected_change_pct >= -100', name='chk_expected_change_pct'),
    sa.CheckConstraint('projected_total IS NULL OR projected_total >= 0', name='chk_projected_total'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lower_bound', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('lower_bound IS NULL OR lower_bound >= 0', name='chk_lower_bound'),
    sa.CheckConstraint('predicted_value IS NULL OR predicted_value >= 0', name='chk_predicted_value'),
    sa.CheckConstraint('upper_bound IS NULL OR upper_bound >= 0', name='chk_upper_bound'),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('demand_benchmarks')
    op.drop_table('reports')
    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_forecast_snapshots_municipality'))

    op.drop_table('forecast_snapshots')
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment=None,
               existing_comment='Municipality centroid latitude, used for marker-level GIS map.',
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment=None,
               existing_comment='Municipality centroid longitude, used for marker-level GIS map.',
               existing_nullable=False)
        batch_op.alter_column('geojson_ref',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Optional reference to a boundary file for future polygon GIS.',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_municipalities_name'), type_='unique')
        batch_op.drop_table_comment(
        existing_comment='Reference table: the seven fixed salt-producing municipalities.'
    )

    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.alter_column('reviewed_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Second FK to users, distinct from submitted_by.',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_production_records_muni_date'))
        batch_op.drop_index(batch_op.f('idx_production_records_status'))
        batch_op.drop_constraint(batch_op.f('production_records_submitted_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('production_records_municipality_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('production_records_reviewed_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'municipalities', ['municipality_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['submitted_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Core operational table: municipal salt production submissions. Canonical units: kg (volume), hectares (area).'
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('municipality_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Required logically for encoder accounts; NULL allowed for admin accounts (province-wide access).',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_municipality_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'municipalities', ['municipality_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='System accounts. role=admin -> ASIN Center Personnel; role=encoder -> BFAR Municipal Coordinator.'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_table_comment(
        'System accounts. role=admin -> ASIN Center Personnel; role=encoder -> BFAR Municipal Coordinator.',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_municipality_id_fkey'), 'municipalities', ['municipality_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('municipality_id',
               existing_type=sa.INTEGER(),
               comment='Required logically for encoder accounts; NULL allowed for admin accounts (province-wide access).',
               existing_nullable=True)

    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Core operational table: municipal salt production submissions. Canonical units: kg (volume), hectares (area).',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('production_records_reviewed_by_fkey'), 'users', ['reviewed_by'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('production_records_municipality_id_fkey'), 'municipalities', ['municipality_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('production_records_submitted_by_fkey'), 'users', ['submitted_by'], ['id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_production_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_production_records_muni_date'), ['municipality_id', 'record_date'], unique=False)
        batch_op.alter_column('reviewed_by',
               existing_type=sa.INTEGER(),
               comment='Second FK to users, distinct from submitted_by.',
               existing_nullable=True)

    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Reference table: the seven fixed salt-producing municipalities.',
        existing_comment=None
    )
        batch_op.create_unique_constraint(batch_op.f('uq_municipalities_name'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('geojson_ref',
               existing_type=sa.VARCHAR(length=255),
               comment='Optional reference to a boundary file for future polygon GIS.',
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment='Municipality centroid longitude, used for marker-level GIS map.',
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               comment='Municipality centroid latitude, used for marker-level GIS map.',
               existing_nullable=False)

    op.create_table('forecast_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('municipality_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('forecast_production', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('growth_rate', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True),
    sa.Column('trend_direction', postgresql.ENUM('increasing', 'stable', 'declining', name='trend_direction_enum'), autoincrement=False, nullable=True),
    sa.Column('production_capacity_forecast', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], name=op.f('forecast_snapshots_municipality_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('forecast_snapshots_pkey')),
    comment='Generated forecast outputs. readiness_status is NEVER stored — computed at runtime by a shared function.'
    )
    with op.batch_alter_table('forecast_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_forecast_snapshots_municipality'), ['municipality_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_type', postgresql.ENUM('provincial', 'municipality', 'forecast', 'data_quality', 'supply_demand', 'gis', name='report_type_enum'), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_range_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_range_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('format', postgresql.ENUM('pdf', 'excel', name='report_format_enum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'generated', 'failed', name='report_status_enum'), server_default=sa.text("'pending'::report_status_enum"), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], name=op.f('reports_municipality_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('reports_requested_by_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey')),
    comment='Generated report records and file references. file_url is a relative path, e.g. under app/static/reports/.'
    )
    op.create_table('demand_benchmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('geographic_scope', postgresql.ENUM('national', 'provincial', name='geographic_scope_enum'), autoincrement=False, nullable=False),
    sa.Column('demand_volume', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('local_production', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('import_volume', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('demand_benchmarks_pkey'))
    )
    op.drop_table('forecast_points')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
